"""initial schema

Revision ID: 658363f61a7e
Revises:
Create Date: 2026-09-30 22:59:05.729939
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "658363f61a7e"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("entity_type", sa.String(length=64), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("actor", sa.String(length=200), nullable=True),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_log_entity_id"), "audit_log", ["entity_id"], unique=False)
    op.create_index(op.f("ix_audit_log_entity_type"), "audit_log", ["entity_type"], unique=False)
    op.create_table(
        "project",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("SOC", "SUBSYSTEM", "IP", name="projectkind", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("is_ip_library", sa.Boolean(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["parent_id"], ["project.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_project_key"), "project", ["key"], unique=True)
    op.create_table(
        "baseline",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("milestone", sa.String(length=120), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("frozen", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.String(length=200), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "name", name="uq_baseline_project_name"),
    )
    op.create_index(op.f("ix_baseline_project_id"), "baseline", ["project_id"], unique=False)
    op.create_table(
        "evidence",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "TEST", "COVERPOINT", "ASSERTION", name="evidencekind", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("fqn", sa.String(length=400), nullable=False),
        sa.Column("name", sa.String(length=400), nullable=False),
        sa.Column("in_git", sa.Boolean(), nullable=False),
        sa.Column("in_regression", sa.Boolean(), nullable=False),
        sa.Column("last_seen_git_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen_regression_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "kind", "fqn", name="uq_evidence_identity"),
    )
    op.create_index(op.f("ix_evidence_fqn"), "evidence", ["fqn"], unique=False)
    op.create_index(op.f("ix_evidence_project_id"), "evidence", ["project_id"], unique=False)
    op.create_table(
        "item_type",
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "base_kind",
            sa.Enum(
                "REQUIREMENT",
                "VERIFICATION_ITEM",
                "OTHER",
                name="itembasekind",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("id_prefix", sa.String(length=16), nullable=False),
        sa.Column("attribute_schema", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "key", name="uq_item_type_project_key"),
    )
    op.create_index(op.f("ix_item_type_project_id"), "item_type", ["project_id"], unique=False)
    op.create_table(
        "regression_run",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("source", sa.String(length=120), nullable=False),
        sa.Column("external_id", sa.String(length=120), nullable=True),
        sa.Column("label", sa.String(length=200), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("imported_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_regression_run_project_id"), "regression_run", ["project_id"], unique=False
    )
    op.create_table(
        "variant",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "key", name="uq_variant_project_key"),
    )
    op.create_index(op.f("ix_variant_project_id"), "variant", ["project_id"], unique=False)
    op.create_table(
        "evidence_result",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("evidence_id", sa.Uuid(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "TEST", "COVERPOINT", "ASSERTION", name="evidencekind", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("passed", sa.Integer(), nullable=True),
        sa.Column("failed", sa.Integer(), nullable=True),
        sa.Column("total", sa.Integer(), nullable=True),
        sa.Column("hits", sa.Integer(), nullable=True),
        sa.Column("goal", sa.Integer(), nullable=True),
        sa.Column("fired", sa.Integer(), nullable=True),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["evidence_id"], ["evidence.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["run_id"], ["regression_run.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "evidence_id", name="uq_result_run_evidence"),
    )
    op.create_index(
        op.f("ix_evidence_result_evidence_id"), "evidence_result", ["evidence_id"], unique=False
    )
    op.create_index(op.f("ix_evidence_result_run_id"), "evidence_result", ["run_id"], unique=False)
    op.create_table(
        "ip_reference",
        sa.Column("consumer_project_id", sa.Uuid(), nullable=False),
        sa.Column("ip_project_id", sa.Uuid(), nullable=False),
        sa.Column("instance_name", sa.String(length=120), nullable=False),
        sa.Column("pinned_ref", sa.String(length=120), nullable=True),
        sa.Column("pinned_baseline_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["consumer_project_id"], ["project.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["ip_project_id"], ["project.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["pinned_baseline_id"], ["baseline.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ip_reference_consumer_project_id"),
        "ip_reference",
        ["consumer_project_id"],
        unique=False,
    )
    op.create_table(
        "item",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("item_type_id", sa.Uuid(), nullable=False),
        sa.Column("human_id", sa.String(length=64), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column(
            "workflow_status",
            sa.Enum(
                "DRAFT",
                "IN_REVIEW",
                "APPROVED",
                name="workflowstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("applicability", sa.String(length=255), nullable=True),
        sa.Column("current_revision_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["item_type_id"], ["item_type.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_item_human_id"), "item", ["human_id"], unique=True)
    op.create_index(op.f("ix_item_project_id"), "item", ["project_id"], unique=False)
    op.create_table(
        "item_revision",
        sa.Column("item_id", sa.Uuid(), nullable=False),
        sa.Column("rev_number", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("ears_pattern", sa.String(length=64), nullable=True),
        sa.Column("author", sa.String(length=200), nullable=False),
        sa.Column("message", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["item_id"], ["item.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("item_id", "rev_number", name="uq_revision_item_number"),
    )
    op.create_index(op.f("ix_item_revision_item_id"), "item_revision", ["item_id"], unique=False)
    # Deferred self-referential FK: item.current_revision_id -> item_revision.id
    # (created after item_revision exists to break the cyclic dependency).
    op.create_foreign_key(
        "fk_item_current_revision",
        "item",
        "item_revision",
        ["current_revision_id"],
        ["id"],
    )
    op.create_table(
        "baseline_entry",
        sa.Column("baseline_id", sa.Uuid(), nullable=False),
        sa.Column("item_id", sa.Uuid(), nullable=False),
        sa.Column("revision_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["baseline_id"], ["baseline.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["item_id"], ["item.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["revision_id"], ["item_revision.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("baseline_id", "item_id", name="uq_baseline_entry_item"),
    )
    op.create_index(
        op.f("ix_baseline_entry_baseline_id"), "baseline_entry", ["baseline_id"], unique=False
    )
    op.create_table(
        "link",
        sa.Column(
            "link_type",
            sa.Enum(
                "DERIVES_FROM",
                "VERIFIED_BY",
                "EVIDENCED_BY",
                name="linktype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("upstream_item_id", sa.Uuid(), nullable=False),
        sa.Column("downstream_item_id", sa.Uuid(), nullable=True),
        sa.Column("downstream_evidence_id", sa.Uuid(), nullable=True),
        sa.Column("reviewed_upstream_revision_id", sa.Uuid(), nullable=True),
        sa.Column("created_by", sa.String(length=200), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "num_nonnulls(downstream_item_id, downstream_evidence_id) = 1",
            name="ck_link_single_downstream",
        ),
        sa.ForeignKeyConstraint(["downstream_evidence_id"], ["evidence.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["downstream_item_id"], ["item.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["reviewed_upstream_revision_id"], ["item_revision.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["upstream_item_id"], ["item.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "link_type",
            "upstream_item_id",
            "downstream_item_id",
            "downstream_evidence_id",
            name="uq_link_endpoints",
        ),
    )
    op.create_index(
        op.f("ix_link_downstream_evidence_id"), "link", ["downstream_evidence_id"], unique=False
    )
    op.create_index(
        op.f("ix_link_downstream_item_id"), "link", ["downstream_item_id"], unique=False
    )
    op.create_index(op.f("ix_link_upstream_item_id"), "link", ["upstream_item_id"], unique=False)
    op.create_table(
        "review",
        sa.Column("item_id", sa.Uuid(), nullable=False),
        sa.Column("revision_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "REQUESTED",
                "IN_REVIEW",
                "CHANGES_REQUESTED",
                "APPROVED",
                name="reviewstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("requested_by", sa.String(length=200), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["item_id"], ["item.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["revision_id"], ["item_revision.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_review_item_id"), "review", ["item_id"], unique=False)
    op.create_table(
        "comment",
        sa.Column("item_id", sa.Uuid(), nullable=False),
        sa.Column("review_id", sa.Uuid(), nullable=True),
        sa.Column("revision_id", sa.Uuid(), nullable=True),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("author", sa.String(length=200), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["item_id"], ["item.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["parent_id"], ["comment.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["review_id"], ["review.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["revision_id"], ["item_revision.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_comment_item_id"), "comment", ["item_id"], unique=False)
    op.create_table(
        "review_assignment",
        sa.Column("review_id", sa.Uuid(), nullable=False),
        sa.Column("reviewer", sa.String(length=200), nullable=False),
        sa.Column("role", sa.String(length=120), nullable=True),
        sa.Column(
            "decision",
            sa.Enum(
                "PENDING",
                "APPROVED",
                "CHANGES_REQUESTED",
                name="reviewdecision",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["review_id"], ["review.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_review_assignment_review_id"), "review_assignment", ["review_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the deferred self-referential FK before dropping item_revision.
    op.drop_constraint("fk_item_current_revision", "item", type_="foreignkey")
    op.drop_index(op.f("ix_review_assignment_review_id"), table_name="review_assignment")
    op.drop_table("review_assignment")
    op.drop_index(op.f("ix_comment_item_id"), table_name="comment")
    op.drop_table("comment")
    op.drop_index(op.f("ix_review_item_id"), table_name="review")
    op.drop_table("review")
    op.drop_index(op.f("ix_link_upstream_item_id"), table_name="link")
    op.drop_index(op.f("ix_link_downstream_item_id"), table_name="link")
    op.drop_index(op.f("ix_link_downstream_evidence_id"), table_name="link")
    op.drop_table("link")
    op.drop_index(op.f("ix_baseline_entry_baseline_id"), table_name="baseline_entry")
    op.drop_table("baseline_entry")
    op.drop_index(op.f("ix_item_revision_item_id"), table_name="item_revision")
    op.drop_table("item_revision")
    op.drop_index(op.f("ix_item_project_id"), table_name="item")
    op.drop_index(op.f("ix_item_human_id"), table_name="item")
    op.drop_table("item")
    op.drop_index(op.f("ix_ip_reference_consumer_project_id"), table_name="ip_reference")
    op.drop_table("ip_reference")
    op.drop_index(op.f("ix_evidence_result_run_id"), table_name="evidence_result")
    op.drop_index(op.f("ix_evidence_result_evidence_id"), table_name="evidence_result")
    op.drop_table("evidence_result")
    op.drop_index(op.f("ix_variant_project_id"), table_name="variant")
    op.drop_table("variant")
    op.drop_index(op.f("ix_regression_run_project_id"), table_name="regression_run")
    op.drop_table("regression_run")
    op.drop_index(op.f("ix_item_type_project_id"), table_name="item_type")
    op.drop_table("item_type")
    op.drop_index(op.f("ix_evidence_project_id"), table_name="evidence")
    op.drop_index(op.f("ix_evidence_fqn"), table_name="evidence")
    op.drop_table("evidence")
    op.drop_index(op.f("ix_baseline_project_id"), table_name="baseline")
    op.drop_table("baseline")
    op.drop_index(op.f("ix_project_key"), table_name="project")
    op.drop_table("project")
    op.drop_index(op.f("ix_audit_log_entity_type"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_entity_id"), table_name="audit_log")
    op.drop_table("audit_log")
    # ### end Alembic commands ###
